[tool.poetry]
name = "main"
version = "0.1.0"
description = ""
authors = ["Aryan Mohanty <aryan.21bce8377@vitapstudent.ac.in>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
